### ISSUE TITLE
Possible P3D render problem on Oreo

### ISSUE THREAD

**Issue by rich-gg** [processing/processing-android#437] opened 2018-02-06 15:51 UTC
I have [this Android app](http://rich.gg/fuzo/FUZObeta3.apk)

When I run it on Nougat it looks like this
http://rich.gg/fuzo/k1nougat.png

And when I run it on Oreo it looks like that
http://rich.gg/fuzo/Screenshot_nexus5Xoreo.png

ps:
+ playing with this to parameters doesn't seem to help
```
         hint(ENABLE_DEPTH_MASK);
         hint(ENABLE_DEPTH_SORT);
```
the whole project can be seen here [here ](https://github.com/rich-gg/FuzoX) on GitHub

**Comment by codeanticode** [comment] 2018-02-06 18:15
Interesting, I noticed the depth flitch when debugging the pause/resume issue on a device with Android 8.1, but I thought it was simply because the app was not finished yet. I will look at it again.

**Comment by rich-gg** [comment] 2018-02-07 07:14
oops, some interesting info [here](https://forum.processing.org/two/discussion/comment/116683#Comment_116683)

kfrajer says he got the bug on a Samsung galaxy S8 **Nougat**

Test so far:
- it works fine with -
Nvidia K1 Nougat
Samsung Galaxy S6 Edge Nougat

- it bugs with -
Nexus 5X Oreo
Mi Mix 2 Oreo
Samsung Galaxy S8 Nougat

Another thing is, the FPS is very low one the Nexus 5X where it bugs

**Comment by codeanticode** [comment] 2018-02-07 15:43
The glitches seem to be related to depth sorting. If you disable it, and draw all spheres without any transparency, does the output look ok?

**Comment by rich-gg** [comment] 2018-02-09 13:37
investigation is going on, and the situation is not exactly simple.

- it seems that the sphere created as a shape  with "createShape(SPHERE, 255)"
might be the culprit (tesselation problem ?)
- but you don't see the problem until you light the sphere with pointLight()

-> as you can see by running this sketch on a Nexus 5X Oreo for instance
When you choose "sphere(255);", no rendering problem
When you choose "shape(globe);", problem

```
    public void settings() {
        fullScreen(P3D);
        smooth();
    }

    private PShape globe;
    private int bgColor = color(245, 245, 236);
    private float fov = 0.2875f;
    private int cameraZ = 2300; //2300


    public void setup() {
        hint(ENABLE_DEPTH_MASK);
        hint(ENABLE_DEPTH_SORT);
        //
        noStroke();
        sphereDetail(48);
        globe = createShape(SPHERE, 255);
        globe.setFill(color(200,0,0));
    }

    public void draw() {
        background(bgColor);

        perspective(fov, PApplet.parseFloat(width) / PApplet.parseFloat(height), 0.1f, 3000);
        camera(0, 0, cameraZ, 0, 0, 0, 0, 1, 0);

        //LIGHTS
        ambientLight(220, 220, 220);
        pointLight(100, 100, 100, -200, 200, 300);
        pointLight(100, 100, 100, 200, -200, 300);

        //GLOBE
        //fill(200,0,0);
        //sphere(255);
        //
        shape(globe);
    }
```

And it would all be nice if I could just replace the shape Sphere with the standard sphere() in my app, but doing so kills the frameRate and messes up the render in its own way

... and removing the pointLight() doesn't solve it either

So my conclusion so far is that the solution lies somewhere where the "createShape(SPHERE, int)" is made.

what do you think ?

Do you need more tests to be done ?

**Comment by codeanticode** [comment] 2018-02-09 21:29
Yes, I think that's the problem. PShape meshes are not depth sorted.

**Comment by rich-gg** [comment] 2018-02-10 13:45
the thing is, it work perfectly fine on certain machines , not on others
and the problem is that is I use sphere() instead, it kills the fps :O

**Comment by codeanticode** [comment] 2018-02-10 16:36
It probably looks fine when you look at the PShape from a specific orientation in which the faces of the sphere are rendered in the correct order in relation to the camera. Transparency in 3D [is hard](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-10-transparency/)!

I think using sphere() is particularly slow not only because it recalculates the vertices in each frame, but also because depth sorting adds an overhead to the rendering... Perhaps you can generate the sphere vertices on your own and store them in an array, and then draw your sphere manually with beginShape()/endShape().

In any case, I'm going to mark this as a duplicate of processing/processing#3484.

**Closed by codeanticode** 2018-02-10 16:36 UTC
Labels: core, duplicate, opengl
