### ISSUE TITLE
I can't export signed aligned pakage

### ISSUE THREAD

**Issue by dinoelectro** [processing/processing-android#656] opened 2021-05-01 09:33 UTC
I can compile and run my sketch on the Android device, but I cannot export the signed and aligned package, an error occurs when trying to export it. the problem always happens it doesn't matter if I compile one program or another. I have all the icons in the folder, I have also modified the xml file and I don't know what else I can do?

**Comment by codeanticode** [comment] 2022-04-18 13:59
This is most likely a duplicate of #646, which has been fixed.

@dinoelectro Please use the following versions that were just released and should properly support generating valid signed/aligned app packages and bundled: 

[Version 4.3.0 for Processing 3](https://github.com/processing/processing-android/releases/tag/latest-processing3)

[Version 4.5.0 alpha3 for Processing 4](https://github.com/processing/processing-android/releases/tag/latest)

**Closed by codeanticode** 2022-04-18 13:59 UTC
Labels: duplicate
