### ISSUE TITLE
image(PGraphics, int, int) crashes on Android 5.1 after initializing PGraphics with createGraphics(..,..,P3D/OPENGL)

### ISSUE THREAD

**Issue by bastova** [processing/processing-android#111] opened 2015-05-30 15:23 UTC
Sample Code:

    PGraphics feedback;  // Image drawn onto by & re-fed to the shader every loop
    public void setup() {

        size(displayWidth, displayHeight, OPENGL);

        noStroke();
        frameRate(60);

        feedback = createGraphics(width/2, height/2, OPENGL);

        feedback.beginDraw();
        feedback.background(0);
        feedback.endDraw();
    }
    public void draw() {

        feedback.beginDraw();

        if (mousePressed) {
            feedback.fill( 255 );
            feedback.noStroke();
            feedback.ellipse( mouseX, mouseY, 100, 100 );
        }

        feedback.endDraw();

        image( feedback, 0, 0 );

        text(frameRate, 10, 10);
    }

There seems to be some sort of GL Error, FrameBuffer is always null. The error occurs on the line where image() is called. Commenting this line out removes the error.

java.lang.NullPointerException: Attempt to invoke virtual method 'int processing.opengl.FrameBuffer.getDefaultDrawBuffer()' on a null object reference
            at processing.opengl.PGraphicsOpenGL.beginPixelsOp(Unknown Source)
            at processing.opengl.PGraphicsOpenGL.readPixels(Unknown Source)
            at processing.opengl.PGraphicsOpenGL.loadPixels(Unknown Source)
            at processing.opengl.PGraphicsOpenGL.initCache(Unknown Source)
            at processing.opengl.PGraphicsOpenGL.getTexture(Unknown Source)
            at processing.opengl.PGraphicsOpenGL$TexCache.getTexture(Unknown Source)
            at processing.opengl.PGraphicsOpenGL.flushPolys(Unknown Source)
            at processing.opengl.PGraphicsOpenGL.flush(Unknown Source)
            at processing.opengl.PGraphicsOpenGL.endDraw(Unknown Source)
            at processing.core.PApplet.handleDraw(Unknown Source)
            at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by bastova** [comment] 2015-05-30 15:25
Sorry, I noticed that this is already a reported bug. I was able to narrow it down a little to the image() method. Maybe this will help a little.

**Comment by codeanticode** [comment] 2015-05-31 22:02
Thanks for posting, will mark it as duplicate of https://github.com/processing/processing-android/issues/53

**Closed by codeanticode** 2015-05-31 22:02 UTC
Labels: duplicate
