### ISSUE TITLE
'Locate SDK path manually' and 'Download SDK automatically' not working

### ISSUE THREAD

**Issue by sooonism** [processing/processing-android#202] opened 2016-04-01 03:10 UTC
It crash my `processing` every time I launch `Android` mode. it will should 2 alerts: 'Locate SDK path manually' and 'Download SDK automatically' panel then `The Android SDK could not be loaded` panel (It blinks, so I believe it launch multiple times).
I click on `OK` so that I can either click  'Locate SDK path manually' and 'Download SDK automatically'. But not of them have any effect. I cannot even quit. So I believe it crash my `processing`.
I am using `OS X 10.11.1` with `Processing 3.0.2`.

**Comment by codeanticode** [comment] 2016-04-05 02:31
Have you had the chance to try the SDK locate/download functionality on a different version of OS X? I have been using 10.10 and didn't see any of these errors, so I wonder if might be related to 10.11. Thanks!

**Comment by Coder-256** [comment] 2016-04-14 21:24
@codeanticode I can confirm that it is not working on OS X El Capitan 10.11.4.

**Comment by codeanticode** [comment] 2016-04-14 21:34
ok, thanks for checking.

**Comment by codeanticode** [comment] 2016-04-14 21:48
@sooonism and @Coder-256: In fact, I was able to reproduce this issue at the end, or at least, a related one. Both buttons 'Locate SDK path manually' and 'Download SDK automatically' did not appear to respond to the mouse, and the first time I had to force quit Processing. The second time the same thing happened, I tried clicking 'Download SDK' without any result but did not quit the app, and after more than a minute, the download actually started and then was able to use Processing normally. I wonder if the same thing is happening to you.

**Comment by Coder-256** [comment] 2016-04-15 00:33
Maybe change [this line](https://github.com/processing/processing-android/blob/a4324246eff7f4f3c8bbedd0ff9c537797141a2e/src/processing/mode/android/AndroidSDK.java#L269) to this:

```Java
EventQueue.invokeLater(new Runnable() {
    @Override
    public void run() {
        JOptionPane.showMessageDialog(window, NOT_ANDROID_SDK);
    }
});
```

As per [this StackOverflow answer](http://stackoverflow.com/a/8550098/3398839).
And if that doesn't work, try passing `null` as the first parameter instead of `window` in the new code.

**Comment by Coder-256** [comment] 2016-04-15 00:35
I just realized that currently the download button does work after some time, but the locate button doesn't.

**Comment by codeanticode** [comment] 2016-04-16 16:21
Just uploaded [RC3](https://github.com/processing/processing-android/releases/tag/latest), please give it a try and let me know if the SDK download works better.

**Comment by Coder-256** [comment] 2016-04-16 19:17
@codeanticode RC3 isn't linked to by [the correct url](https://github.com/processing/processing-android/releases/latest), not sure why. I can't update.

**Comment by codeanticode** [comment] 2016-04-16 20:44
It might take a while to show up on the Contribution Manager until the indexes are updated, but you can install RC3 manually by downloading the .zip file, unpack it, and then copy it to the mode folder inside your sketchbook folder.

**Comment by Coder-256** [comment] 2016-04-18 14:48
@codeanticode What I meant is that you should have tagged it `android-0250` instead of `latest`.

It does work if I use the method you showed me. The only problem is that Processing hangs if you cancel the setup in any way (cancelling the file dialog, cancelling the download, or closing the window).

**Comment by codeanticode** [comment] 2016-05-03 21:02
latest is always identical to the most recent release (because the CM requires a static URL), which right now is 0249: https://github.com/processing/processing-android/tags

I have been testing the locate and download options, and they seem to work fine, although only most of the time. Sometimes the PDE hangs after canceling the download or the locate, which is reported separately https://github.com/processing/processing-android/issues/209. It seems an error in the class loader though, and not related to the SDK download UI.

**Comment by codeanticode** [comment] 2016-05-07 06:56
A temporary workaround for the PDE freeze issue is to disable the "Suggest import statements" option in the Preferences.

**Closed by codeanticode** 2016-05-07 06:56 UTC
