### ISSUE TITLE
none sketches work on my phone

### ISSUE THREAD

**Issue by cjdg** [processing/processing-android#322] opened 2017-04-19 23:58 UTC
Im trying to use Processing Android but none of the sketches works on my phone, i have a moto g4 plus with android 7 and all the sketches mark a "the application continues crashing"

**Comment by jdawwwggo** [comment] 2017-04-20 11:26
same,

**Comment by codeanticode** [comment] 2017-04-23 21:26
Do you get any error log in the PDE's console? If not, could you run adb logcat and post the error here? Thank you!

**Comment by cjdg** [comment] 2017-04-26 16:31
At the end i installed the latest android studio and then now i have the ant issue so now i cant even compile...

**Comment by codeanticode** [comment] 2017-04-26 22:50
Not sure what's the reason for this problem, but please note that the latest SDK tools breaks the mode, as reported [here](https://github.com/processing/processing-android/issues/307) and [here](https://github.com/processing/processing-android/issues/321). We are currently working to solve this issue, but in the meantime, you should make sure that you are not using any version of the SDK tools higher than 25.2.0, SDK build tools higher than 25.0, and platform tools higher than 25.0

**Comment by codeanticode** [comment] 2017-08-08 16:00
@cjdg @jonathanreade could you confirm if you still have these issues with the [release candidate](https://github.com/processing/processing-android/releases/tag/android-264)?

**Comment by codeanticode** [comment] 2017-08-15 12:12
Haven't received updates from origina poster, and unable to reproduce, closing.

**Closed** 2017-08-28 13:41 UTC
Labels: needs confirmation
