### ISSUE TITLE
White screen when setting P3D and orientation to landscape

### ISSUE THREAD

**Issue by emnullfuenf** [processing/processing-android#104] opened 2015-03-29 15:01 UTC
When i am setting the orientation to landscape and the renderer to P3D i'm getting a white screen on Motorola Moto G 2014 and a LG Nexus 4 (both Android 4.4.4). And the sketch freezes. Setting either landscape or P3D works.

Processing console reports this when P3D is enabled:
"debug:
Smooth is not supported by this hardware (or driver)"

println in draw() does not print since the sketch is stuck.

Android debugging console does not raise any error.

Code:
    void setup()
    {
        size(displayWidth, displayHeight, P3D);
        orientation(LANDSCAPE);
    }
    void draw()
    {
      fill(random(255), random(255), random(255));
      rect(200, 200, 200, 200);
      println("draw");
    }

**Comment by emnullfuenf** [comment] 2015-03-29 15:27
It seems to work when i set landscape orientation in AndroidManifext.xml:

<activity android:name="" android:screenOrientation="landscape">

But only when the device screen is active when launched. If the screenlock is active i'll it's stuck at the background color of the sketch.

**Comment by omerjerk** [comment] 2015-03-29 16:12
A call to `orientation()` changes the orientation of app at runtime. The app first starts in portrait and then rotates by 90 degree. White screen could be due to processing-core not fully complying with the activity life cycle events. I'll probably have a look at it.

**Comment by codeanticode** [comment] 2015-06-23 19:22
landscape orientation should not result in a white screen, @omerjerk have you experienced a similar behavior?

**Comment by omerjerk** [comment] 2015-06-23 19:51
I haven't experienced anything like this. I was just thinking that orientation should be hardcoded in AndroidManifest.xml. Though, I can't really think of any downsides of the current approach.

**Comment by codeanticode** [comment] 2016-04-16 16:41
Cannot reproduce, and no updates from original poster. Closing.

**Closed** 2016-04-16 16:41 UTC
