### ISSUE TITLE
Mirrored/inverted coordinates using PGraphics and LiveWallpaper

### ISSUE THREAD

**Issue by danieltorrer** [processing/processing-android#357] opened 2017-07-13 04:08 UTC
I came across a a bug in Live Wallpaper mode: 

If you use PGraphics and draw it using `image` the result is a image with the coordinates mirrored.

Code:
```
PGraphics canvas;

void setup() {
  //fullScreen(P3D);
  size(540, 960, P3D);
  canvas = createGraphics(width/2, height/2, P3D);
}

void draw() {
  background(#D403FF);
  
  canvas.beginDraw();
  canvas.background(#36FFCB);
  canvas.sphere(100);
  //canvas.ellipse( 30, 30, 100, 100);
  canvas.endDraw();
  
  image(canvas, 50, 50);
}
```

Using Java Mode (default) :
![Imgur](http://i.imgur.com/or2hGAE.png)

Live Wallpaper: 
![Imgur](http://i.imgur.com/xCuVjuY.png)

Processing: 3.3.5
Processing-android: 4.0-beta9 (Android Mode 0262)
OS X: 10.10.5
Android: 6.0.1 (Tested in a MotoX Play and a Alcatel Pop 4 Plus)

**Comment by codeanticode** [comment] 2017-07-13 11:27
@danieltorrer thanks for the report, I will look into it asap!

**Comment by codeanticode** [comment] 2017-07-13 19:23
Fixed with https://github.com/processing/processing-android/commit/3d5e943dd24a96979befd871c2d473d0c053fe85, was due to a regression introduced with the support for VR. The next version of the mode (hopefully a "release candidate" before pushing the new stable through the Contributions Manager) will include this fix.

**Closed by codeanticode** 2017-07-13 19:23 UTC
Labels: core

**Comment by danieltorrer** [comment] 2017-07-13 21:05
Great, can't wait to use the rc. 
Thanks for this awesome library

**Comment by codeanticode** [comment] 2017-07-15 17:48
The rc is coming along quite well, but still a few weeks away. You can try this last beta that includes the coordinate inversion fix:

https://github.com/processing/processing-android/releases/tag/android-263
