### ISSUE TITLE
Can't run processing after switching to android mode

### ISSUE THREAD

**Issue by cjdg** [processing/processing-android#401] opened 2017-08-31 19:53 UTC
Ubuntu Studio 16.04.3 x64
Processing 3.3.5
Android Mode 0266

After switching to Android Mode, it hangs on a screen which says "SDK configured!" and stays there, i send picture
![seleccion_039](https://user-images.githubusercontent.com/5726836/29942618-2a04409a-8e5c-11e7-9c16-19a9a91486e3.png)

**Comment by codeanticode** [comment] 2017-09-01 13:04
@cjdg This happens if you choose to use an SDK already present in the system, right? 

What happens if you close Processing and open it again? Does it still show this message?

**Comment by codeanticode** [comment] 2017-09-01 23:23
I run some tests on a similar setup (Ubuntu 16.0.4 x64, Processing 3.3.5, Android mode 0266), and just in one occasion I saw a similar problem (the message dialog freezing Processing's UI). The rest of the time, the dialog showed up without problem. My guess is that this is due to some but/quirk in Swing.

**Comment by cjdg** [comment] 2017-09-06 05:25
Well it always happens to my setup, even cant close the window, i have to use xkill to do it

**Comment by codeanticode** [comment] 2017-09-07 15:06
When you xkill the PDE, and start it again, isn't the SDK recognized when the switch to the android mode?

**Comment by codeanticode** [comment] 2018-01-22 21:28
Did not hear back from the OP and cannot reproduce, closing.

**Closed by codeanticode** 2018-01-22 21:28 UTC
