### ISSUE TITLE
The Tablet Screen rotates, and sometimes (infrequently) I can get this error. (Version 258 Beta-5)

### ISSUE THREAD

**Issue by TrW236** [processing/processing-android#325] opened 2017-04-23 16:24 UTC
```
java.lang.OutOfMemoryError: Failed to allocate a 9216012 byte allocation with 5538600 free bytes and 5MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
	at processing.a2d.PGraphicsAndroid2D.allocate(Unknown Source)
	at processing.core.PGraphics.setSize(Unknown Source)
	at processing.android.PWallpaper$WallpaperEngine.onSurfaceChanged(Unknown Source)
	at android.service.wallpaper.WallpaperService$Engine.updateSurface(WallpaperService.java:798)
	at android.service.wallpaper.WallpaperService$Engine.attach(WallpaperService.java:908)
	at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1200)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7303)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by codeanticode** [comment] 2017-04-27 03:43
The rotation issue #324 should be fixed now, but not sure if there is much that can be done about this one: the screen bitmap [is recycled](https://github.com/processing/processing-android/blob/master/core/src/processing/a2d/PGraphicsAndroid2D.java#L174) before recreating it when a resize evens happens, which [should fee up](https://developer.android.com/reference/android/graphics/Bitmap.html#recycle()) the native resources taken up by the bitmap. If the device is running low on memory, the GC might not kick in fast enough to release enough memory for the new object, and then the OutOfMemoryError crash.

**Comment by codeanticode** [comment] 2017-04-27 04:09
Actually, he function [Bitmap.reconfigure()](https://developer.android.com/reference/android/graphics/Bitmap.html#reconfigure(int, int, android.graphics.Bitmap.Config)) allows to change the width and height of the bitmap, if the new resolution takes no more memory than the original one. This is precisely the case of a screen rotation. I tested it briefly after this [commit](https://github.com/processing/processing-android/commit/2ba7381ba6c0d20ccf36c618fa2a991f4dbfab60), and does not seem to hurt. Once the next version of the mode is available, try it on your device to see if the crashes go away.

**Comment by codeanticode** [comment] 2017-08-08 16:01
@TrW236 could you test the [release candidate](https://github.com/processing/processing-android/releases/tag/android-264) package and let me know if you still get this crash? Thanks!

**Comment by codeanticode** [comment] 2017-08-28 13:41
No confirmation from original poster, and not able to reproduce it.

**Closed by codeanticode** 2017-08-28 13:41 UTC
Labels: core, needs confirmation
