### ISSUE TITLE
multiple overlapping partial transparent png issues

### ISSUE THREAD

**Issue by jwindberg** [processing/processing-android#89] opened 2014-12-12 05:50 UTC
I'm rotating two png images around the screen. big round dots, with transparent backgrounds.
The second image draw wipes out the first, leaving the background showing through.
The images draw correctly on windows, this is an android oddity.

**Comment by erkosone** [comment] 2016-02-03 22:56
i have the same problem,
If i use textFont() with any PGraphics object i wipe the alpha channel from all images.


I think it's the same thing happens to you, you used textFont ()? I have not reported this error .. if you're using can try to not use it can say that this will work?

**Comment by ZachSundberg** [comment] 2016-02-26 17:48
Same problem when using textFont()
I will report.

**Comment by erkosone** [comment] 2016-03-04 15:50
any solution for this bug?

**Comment by codeanticode** [comment] 2016-03-04 20:00
@erkosone @ZachSundberg the font-related issue appears to be a duplicate of https://github.com/processing/processing-android/issues/196, which I fixed recently.

@jwindberg I'm trying to reproduce your original issue with the following code:

```java
PImage img1;
PImage img2;

void setup() {
  fullScreen();
  img1 = loadImage("dotR.png");
  img2 = loadImage("dotG.png");
  imageMode(CENTER);
}

void draw() { 
  background(160);
  line(0, 0, width, height);
  line(width, 0, 0, height);

  image(img1, width/2, height/2);
  image(img2, mouseX, mouseY);
}
```

and these two images:

![dotg](https://cloud.githubusercontent.com/assets/62246/13538618/b1f1c6b2-e219-11e5-898f-14167b13838a.png)
![dotr](https://cloud.githubusercontent.com/assets/62246/13538621/b55aa72e-e219-11e5-9493-dd55df316ba4.png)

but don't see anything wrong. Could you confirm if still happens to you with the latest version of the mode running in Processing 3.0.2, and post the code if so?

**Comment by erkosone** [comment] 2016-03-05 08:44
This example works well, but in my programs are going wrong, I'm working to reproduce the error with the minimum code, I share when I get ready. thank you.

**Comment by erkosone** [comment] 2016-03-05 08:48
I have, this is the code that reproduces the error:

```
PImage img1;
PImage img2;
PFont  fnt1;

void settings(){
  size(640, 400, P2D);
}

void setup() {
  fullScreen();
  img1 = loadImage("dotR.png");
  img2 = loadImage("dotG.png");
  imageMode(CENTER);
  fnt1 = loadFont("Cambria-48.vlw");
}

void draw() { 
  textFont(fnt1);    // THIS IS THE BUG GENERATOR LINE!!!!!!!!!
  background(160);
  line(0, 0, width, height);
  line(width, 0, 0, height);
  
  translate(width/2, height/2);
  image(img1, 0, 0);
  translate(mouseX, mouseY);
  image(img2, 0, 0);
  text("EXAMPLE TEXT", 100, 100);
}
```

**Comment by erkosone** [comment] 2016-03-05 08:50
The problem is that you can not use the default render android because it is extremely slow and to make any necessary game graphics acceleration of P2D P3D.

I'm looking forward the settlement of this problem;)

**Comment by ZachSundberg** [comment] 2016-03-05 13:08
Looks like this issue has been resolved here:
https://github.com/processing/processing-android/issues/196

**Comment by erkosone** [comment] 2016-03-05 16:50
Perfect! it seems that this has been resolved, it's great.
As I can update my android mode to enjoy this improvement?
you have to wait for a new release? or you can download some way at this time?
Thanks for the info ;)

**Comment by codeanticode** [comment] 2016-03-05 21:40
Use the [RC1 release](https://github.com/processing/processing-android/releases/tag/latest) of the mode.

**Closed by codeanticode** 2016-03-05 21:40 UTC
