### ISSUE TITLE
Application randomly (mostly) crashed at start.

### ISSUE THREAD

**Issue by unrealkate** [processing/processing-android#253] opened 2016-09-21 15:35 UTC
When building sketch with Processing IDE 3.2.1 in Android Mode on PC, installed APK fails to start on mobile phone, randomly crashing at start. After hitting the icon several times it might run well. Same sketch compiled with APDE on the phone itself runs perfectly. 

My phone is: Philips Xenium I908 (with FullHD display 1920x1080 and 2 GB RAM)
My pc runs: Windows 8.1 Pro x64 and Processing 3.2.1 (x64) + Android Mode 3.0.1

Processing IDE gives me this when app crashes:

> java.lang.NullPointerException
>     at processing.core.PGraphicsAndroid2D.backgroundImpl(Unknown Source)
>     at processing.core.PGraphics.backgroundFromCalc(Unknown Source)
>     at processing.core.PGraphics.background(Unknown Source)
>     at processing.core.PGraphics.defaultSettings(Unknown Source)
>     at processing.core.PGraphics.checkSettings(Unknown Source)
>     at processing.core.PGraphicsAndroid2D.beginDraw(Unknown Source)
>     at processing.core.PApplet.handleDraw(Unknown Source)
>     at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
>     at processing.core.PApplet.run(Unknown Source)
>     at java.lang.Thread.run(Thread.java:841)
> FATAL EXCEPTION: Animation Thread
> Process: processing.test.sketch_160921a, PID: 5683
> java.lang.NullPointerException
>     at processing.core.PGraphicsAndroid2D.backgroundImpl(Unknown Source)
>     at processing.core.PGraphics.backgroundFromCalc(Unknown Source)
>     at processing.core.PGraphics.background(Unknown Source)
>     at processing.core.PGraphics.defaultSettings(Unknown Source)
>     at processing.core.PGraphics.checkSettings(Unknown Source)
>     at processing.core.PGraphicsAndroid2D.beginDraw(Unknown Source)
>     at processing.core.PApplet.handleDraw(Unknown Source)
>     at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
>     at processing.core.PApplet.run(Unknown Source)
>     at java.lang.Thread.run(Thread.java:841)

**Comment by unrealkate** [comment] 2016-09-21 15:44
Tested with the following simple sketch:
> void setup()
> {
>   fullScreen();
> }
> void draw()
> {
>   background(50);
>   stroke(250);
>   fill(150);
>   ellipseMode(RADIUS);
>   ellipse(width / 2, height / 2, 200, 200);
> }
> 

I tried to remove a call to background() function but with no success.

**Comment by sesmusician** [comment] 2016-09-27 20:02
try  fullScreen(P2D);
fixed the problem to me,but it is slower and it looks ugly.

**Comment by brew4321** [comment] 2016-09-28 04:49
I've been making a game and it kept crashing. (I had the same error you do, and it sometimes works, and sometimes doesn't). I started to suspect it had something to do with PVectors so I whittled the code down to the following minimal program that still gives me the error:
```
PVector v1;
PVector v2;
size(640,360);
v1 = new PVector(0,1);
v2 = new PVector(1,2);
v1.add(v2);
```
I was going to open a new issue here, but just saw yours.
Also I noticed the size function seems to be critical to the error. If I try it with out the size function the error goes away and it starts every time. Or if I use smaller numbers like `size(50,50);` it also goes away. Since your simple sketch has `fullScreen` that may be a place to start debugging...

**Comment by darioringach** [comment] 2016-11-08 21:18
My settings() has only two lines, fullScreen(JAVA2D) and orientation(LANDSCAPE).

I noticed that adding a 1s delay after each dramatically reduced the number of instances where the program crashes with the above error (from 50% to about 2%).

**Comment by codeanticode** [comment] 2016-11-09 00:28
@darioringach thanks for this info, sounds like could be useful to determine the cause of the crash!

**Comment by raft75** [comment] 2016-11-18 06:29
I have the same problem on a Galaxy S3 (Android 4.4.2).
@darioringach Could you share the code you are using to mitigate the issue? I have tried with delay(1000) but it doesn't help.

**Comment by rossanag** [comment] 2017-01-16 21:54
I am having the same problem with an LG 2 Mini Android 4.4.2
Here it is the whole description:

**I tested the example that is in the Processing Android page:**
```

    import android.content.Context;
    import android.hardware.Sensor;
    import android.hardware.SensorManager;
    import android.hardware.SensorEvent;
    import android.hardware.SensorEventListener;

    Context context;
    SensorManager manager;
    Sensor sensor;
    AccelerometerListener listener;
    float ax, ay, az;

    void setup() {
      fullScreen();
      //size(displayWidth, displayHeight);
      context = getActivity();
      manager = (SensorManager)context.getSystemService(Context.SENSOR_SERVICE);
      sensor = manager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);
      listener = new AccelerometerListener();
      manager.registerListener(listener, sensor, SensorManager.SENSOR_DELAY_GAME);

      textFont(createFont("Arial", 60));
    }

    void draw() {
      background(0);
      text("X: " + ax, 10, 60);
      text("Y: " + ay, 10, 120);
      text("Z: " + az, 10, 180);
    }

    class AccelerometerListener implements SensorEventListener {
      public void onSensorChanged(SensorEvent event) {
        ax = event.values[0];
        ay = event.values[1];
        az = event.values[2];    
      }
      public void onAccuracyChanged(Sensor sensor, int accuracy) {
      }
    }


    public void onResume() {
      super.onResume();
      if (manager != null) {
        manager.registerListener(listener, sensor, SensorManager.SENSOR_DELAY_GAME);
      }
    }

    public void onPause() {
      super.onPause();
      if (manager != null) {
        manager.unregisterListener(listener);
      }
    }

```   
 I got the following error and the app doesn't even start:

    FATAL EXCEPTION: Animation Thread
```
    Process: processing.test.and1, PID: 13795
    java.lang.NullPointerException
        at processing.core.PGraphicsAndroid2D.backgroundImpl(Unknown Source)
        at processing.core.PGraphics.backgroundFromCalc(Unknown Source)
        at processing.core.PGraphics.background(Unknown Source)
        at processing.core.PGraphics.defaultSettings(Unknown Source)
        at processing.core.PGraphics.checkSettings(Unknown Source)
        at processing.core.PGraphicsAndroid2D.beginDraw(Unknown Source)
        at processing.core.PApplet.handleDraw(Unknown Source)
        at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
        at processing.core.PApplet.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:841)

```
   
 I had to modify the code and put **size(displayWidth, displayHeight);** instead and it works fine.


    Processing version: 3.2.3
    Android Mode: 3.0.2 (installed through the IDE)
    Target SDK: API 6.0 (23)
    OS: Ubuntu 12.04 64 bits

    Hope I could have any hint to solve this.

**Comment by rossanag** [comment] 2017-01-16 22:08
UPDATE: When tested with Target SDK: API 7.1.1 is working. I will check out another examples.

**Comment by rossanag** [comment] 2017-01-16 22:14
If I load an image: png, jpg, it doesn't work in any Target SDK I tryed.

**Comment by exal99** [comment] 2017-01-28 19:48
I get exactly the same exception but only when I run my app on my Samsung taplet with API 16, Android 4.1.2. However when I run it on my phone (API 23 Android 6.0.1) everything works just fine. I also get it to work when I use P2D as the renderer but it runs painfully slow. During it's run I'm also noticing a lot of calls to the garbage collector. Is the problem that processing dose not support older android versions?

**Comment by Calsign** [comment] 2017-02-28 21:35
Instead of P2D, it appears that using OPENGL avoids both the default renderer crash and the poor performance of P2D. See the issue [APDE #24](https://github.com/Calsign/APDE/issues/25#issuecomment-282572066) for more information.

**Comment by codeanticode** [comment] 2017-03-10 22:20
Hi there, I'm testing the sketches posted by @rossanag and @unrealkate on the latest beta release of the mode ([4.0-beta5](https://github.com/processing/processing-android/releases/tag/android-258)), but cannot get any crashes. Maybe this is due to some bug in the earlier stable branch (3.x), but already fixed in the 4.x branch.

As a quick note, there is no need to use onResume/onPause, just put the code inside the resume/pause functions, which will get automatically called when the onResume and onPause events are triggered:

```
import android.content.Context;
import android.hardware.Sensor;
import android.hardware.SensorManager;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;

Context context;
SensorManager manager;
Sensor sensor;
AccelerometerListener listener;
float ax, ay, az;

void setup() {
  fullScreen();
  //size(displayWidth, displayHeight);
  context = getActivity();
  manager = (SensorManager)context.getSystemService(Context.SENSOR_SERVICE);
  sensor = manager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);
  listener = new AccelerometerListener();
  manager.registerListener(listener, sensor, SensorManager.SENSOR_DELAY_GAME);

  textFont(createFont("Serif", 60));
}

void draw() {
  background(0);
  text("X: " + ax, 10, 60);
  text("Y: " + ay, 10, 120);
  text("Z: " + az, 10, 180);
}

class AccelerometerListener implements SensorEventListener {
  public void onSensorChanged(SensorEvent event) {
    ax = event.values[0];
    ay = event.values[1];
    az = event.values[2];
  }
  public void onAccuracyChanged(Sensor sensor, int accuracy) {
  }
}

void resume() {
  if (manager != null) {
    manager.registerListener(listener, sensor, SensorManager.SENSOR_DELAY_GAME);
  }
}

void pause() {
  if (manager != null) {
    manager.unregisterListener(listener);
  }
}
```

**Comment by rossanag** [comment] 2017-03-10 22:58
@codeanticode, @Calsign I haven't had time to try what you both suggested (I have in mind that I used OPENGL as a parameter, not sure though).
As soon as I could I will post my results. Thanks a lot!

**Comment by raft75** [comment] 2017-03-11 06:44
@codeanticode 
Have you tried older devices and/or emulators with older API ? 
I have this problem on a Galaxy S3 (Android 4.4.2) but never experienced it on newer devices (Android 5.1)

**Comment by raft75** [comment] 2017-03-11 11:50
I have published an app made with Android mode 3.0.1:
https://play.google.com/store/apps/details?id=com.raffaeletasso
According to Google Play Developer Console users get the error reported by @unrealkate and @rossanag on Android 4.3 and Android 4.4
On Android 4.2 users get a slightly different error (the last line is Thread.java:856 instead of Thread.java:841). 
Java.lang.NullPointerException
	at processing.core.PGraphicsAndroid2D.backgroundImpl(Unknown Source)
	at processing.core.PGraphics.backgroundFromCalc(Unknown Source)
	at processing.core.PGraphics.background(Unknown Source)
	at processing.core.PGraphics.defaultSettings(Unknown Source)
	at processing.core.PGraphics.checkSettings(Unknown Source)
	at processing.core.PGraphicsAndroid2D.beginDraw(Unknown Source)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:856)

Updating to Android mode 3.0.2 didn't help.

**Comment by codeanticode** [comment] 2017-03-11 15:38
[backgroundImpl()](https://github.com/processing/processing-android/blob/android-0253-v3.0.2/core/src/processing/core/PGraphicsAndroid2D.java#L1822) just calls canvas.drawColor(), so the only possibility for the NPE is that the canvas object is NULL. This has not changed between the 3.x and 4.x versions.

The canvas is initialized in the allocate() method, which is called from setSize(). In turn, setSize() is called from the onSurfaceChanged() event handlers in the renderers, so this could then be due to a threading issue (note that allocate() is not used in the GL renderers, only in A2D). I will look into it.

However, any fix will be available only in the 4.x branch, so you will need to update to a beta release in order to get the fix.

**Comment by raft75** [comment] 2017-03-11 16:35
@Calsign I have tried OPENGL as you suggested but in my app text becomes unreadable, so for me it's not an option.
@codeanticode I have tried Android Mode 4.0-beta5, my app compiles but then fails to start on Samsung S3 Neo without any errors on console. Are existing sketches (working with Android Mode 3.02) supposed to work with Android Mode 4.0-beta5 out of the box ?
Is it correct to put in preferences.txt the following settings for Android Mode 4.0-beta5 ?
android.sdk.name=7.1.1
android.sdk.version=25

**Comment by codeanticode** [comment] 2017-03-11 16:51
@raft75 Existing sketches should work with the new beta, did you try any of the provided examples?

beta5 requires Android 25, so setting those values in the preferences file should be ok. However, I'd recommend to just replace the AndroidMode folder with the new one, restart Processing and let the mode to download a fresh copy of the SDK.

**Comment by raft75** [comment] 2017-03-11 18:25
@codeanticode
First of all, thanks for support and for dedicating your spare time to Processing. 
Following your suggestion, I let Android Mode 4.0-beta5 download a fresh SDK, and I deleted preferences.txt to let it build a fresh one. Unfortunately my app does not start and I don't see any errors in console.
I tried a new sketch containing only this:
void settings() {
 orientation(LANDSCAPE); //ANDROID
}
void draw() {
 background(204); 
}
It does not start as well. If I comment out orientation(LANDSCAPE) it starts and I admire an empty gray screen. Going back to my app and commenting out orientation(LANDSCAPE), unfortunately it does not start, I don't have any clue for what reason.
Now my question is, what is the minimum Android version supported by Android Mode 4.x? 
My Galaxy S3 Neo (Android 4.4.2) seems very far from being supported.

**Comment by codeanticode** [comment] 2017-03-11 19:04
Don't use orientation() inside settings, only the size, fullScreen, and smooth functions [can be called there](https://processing.org/reference/settings_.html). However, you should see an error message in the console, not sure why is not showing up. Do you get the output of a println() in the console?

The minimum Android version supported is is 4.1. I will let you know when a new version beta is available with a potential fix for the random crash.

**Comment by rossanag** [comment] 2017-03-11 19:41
@codeanticode  I update Android Mode to beta version you suggested, and I tried the code you pasted.
It was tested on device.
Android 4.4.2
SDK API 6.0  (23) 
OS: Ubuntu 12.04 64 bits.
Processing: last version

First I saw this message:
`_blendMode(), or this particular variation of it, is not available with this renderer._`

As soon as I change the orientation it crashes and the texts are displayed in a very small size, that are barely visible.

And if I run it again, here is the error:
```
FATAL EXCEPTION: Animation Thread
Process: processing.test.androidtest, PID: 28440
java.lang.NullPointerException
	at processing.core.PGraphicsAndroid2D.backgroundImpl(Unknown Source)
	at processing.core.PGraphics.backgroundFromCalc(Unknown Source)
	at processing.core.PGraphics.background(Unknown Source)
	at processing.core.PGraphics.defaultSettings(Unknown Source)
	at processing.core.PGraphics.checkSettings(Unknown Source)
	at processing.core.PGraphicsAndroid2D.beginDraw(Unknown Source)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)

```

@codeanticode @Calsign If I put OPENGL as the parameter un fullScreen, it works without crashing.
There's a sort of blink at every orientation change, but it works. 
Why does blink happen?-

**Comment by codeanticode** [comment] 2017-03-11 19:52
@rossanag the message means that blendMode() is not available in the default (Android2D) renderer. You need to switch to the OpenGL renderers (P2D or P3D) to be able to use it.

Not sure about the reason for the orientation crash, I haven't experienced it myself. You can go ahead and open a separate issue about it, with some sample code.

And as for the NullPointerException at backgroundImpl(), I may have as solution for it, but haven't pushed a new beta release yet that includes the potential fix.

**Comment by rossanag** [comment] 2017-03-11 20:18
@codeanticode thanks for the explanation, the orientation crash happens if I don't put the OPENGL parameter, otherwise it works (maybe I wasn't clear enough).

I don't understand if I shouldn't experience it without the parameter either and that's what the reason you suggested me to open a new issue.
Thanks so much for your time

**Comment by raft75** [comment] 2017-03-11 21:14
@codeanticode 
Even if I don't use orientationI() at all my app does not start with Android Mode 4.0-beta5.
And unfortunately the following code does not produce any output in the console (it does in Java mode or in Android Mode 3.x)
void draw() {
  background(204);
  println("test");
}

**Comment by raft75** [comment] 2017-03-11 21:28
@codeanticode 
I have tried the following code on a different device:
void draw() {
background(204);
println("test");
}
The device is a tablet Lenovo TAB 2 A10-70F, Android 4.4.4
The sketch starts and in the console prints:
AndroidDevice: cannot find process id, console output will be disabled.

**Comment by codeanticode** [comment] 2017-08-12 18:28
@unrealkate raft75 @rossanag @exal99 @brew4321 @darioringach The latest [release candidate](https://github.com/processing/processing-android/releases/tag/android-265) might solve some of these issues... give it a try if you chance. Thank you!

**Comment by raft75** [comment] 2017-08-19 13:05
I have a sketch that in Android mode 3.x sometimes has this issue (crash on start) on some devices (like Samsung S3 Neo).
Unfortunately with the latest release candidate it always crashes, I don't have any output console because of https://github.com/processing/processing-android/issues/331.
Please find attached adb logcat output.
[log.zip](https://github.com/processing/processing-android/files/1236359/log.zip)

**Comment by codeanticode** [comment] 2017-08-19 13:58
@raft75 Try deleting the manifest file and running the sketch again from the latest RC of the mode. I found this exception in the log:

W/System.err( 4439): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.raffaeletasso/com.raffaeletasso.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

which makes me think this is probably the issue. Version 3.x of the mode uses a theme that that is not compatible with 4.x (added a mention to this in the [what's new page](http://android.processing.org/whatsnew.html))

**Comment by raft75** [comment] 2017-08-19 20:41
Thanks for the support, now it works.
I had to make a small change (from previous version working with Version 3.x)

Version 3.x:
void settings() {
orientation(LANDSCAPE);
size(displayWidth, displayHeight);
}

Version 4 release 265:
void setup() {
orientation(LANDSCAPE);
}

**Comment by raft75** [comment] 2017-08-19 20:48
I'm very happy to say that I cannot reproduce issue #253 with release 0265.

**Comment by codeanticode** [comment] 2017-08-19 21:08
Great! Some notes about the size function: if you don't include a size() call in setup(), then the sketch will launch in fullscreen mode, hiding both the navigation and the status bars. This is equivalent to adding fullScreen() explicitly to setup(). You should be able to use size(displayWidth, displayHeight) in version 4 of the mode, the difference with true fullscreen is that the sketch will use the entire screen but keeping the navigation and status bars in place.

Since I haven't heard from any of the other posters in this thread, and seems like people were reporting different problems (several of which are probably fixed in the RCs), I'm going to close this issue. People can open new ones as they find new issues with the RCs and the upcoming stable release.

**Closed by codeanticode** 2017-08-19 21:08 UTC
Labels: bug, core, needs confirmation
