### ISSUE TITLE
Hyperlink error on tutorial page click

### ISSUE THREAD

**Issue by rupeshkumar22** [processing/processing-android#631] opened 2021-01-03 19:52 UTC
Faced an error while trying to open a tutorial hyperlink mentioned in the dialog box. 
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.mode.android.AndroidUtil$1.hyperlinkUpdate(AndroidUtil.java:78)
	at javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:342)
```
![linkerrorIssue](https://user-images.githubusercontent.com/46577873/103487408-2bc7b280-4e2b-11eb-96db-536cf897c7bc.JPG)

**Comment by rupesh-kumar-lpu** [comment] 2021-01-03 19:56
I think this is the duplicate of #436

**Comment by codeanticode** [comment] 2023-03-17 20:12
Fixed with https://github.com/processing/processing-android/commits/main

**Closed by codeanticode** 2023-03-17 20:12 UTC
Labels: bug, mode, needs confirmation
