### ISSUE TITLE
Cardboard - Cannot access com.google.vr.sdk.base.*;

### ISSUE THREAD

**Issue by caru** [processing/processing-android#301] opened 2017-02-21 09:00 UTC
I am not sure if this is an issue or not...

I need to access the HeadTransform, so at the beginning of the sketch I have:
import com.google.vr.sdk.base.*;

But when I try to run the sketch, the console shows this error:
No library found for com.google.vr.sdk.base

I think I need to access the HeadTransform to know where the user is aiming at, or maybe I am missing something?

**Comment by caru** [comment] 2017-02-21 16:11
Actually, it looks like that is not the real problem. The real problem, as far as I understand, is that there is no way in the draw() method to get the head rotation from the HeadTransform or from PGraphicsCardboard. This makes it impossibile to interact with the world, except looking around which is already performed automatically... sorry if I am missing something but there is no tutorial around beside the "getting started" one and understanding how it all works is really overwhelming.

**Comment by codeanticode** [comment] 2017-02-21 16:23
@caru Thanks for reporting this issue! The problem is that the GVR packages are currently inside the lib folder in AndroidMode/libraries/cardboard, but should be inside library instead. A quick workaround is to copy the jar files to cardboard/library (don't move them, they are also needed in lib). This will be fixed in the next release of the mode.

**Comment by caru** [comment] 2017-02-21 17:10
@codeanticode Thank you for the quick reply!

However, looking again at the examples, I found a solution to my problem... so simple that I cannot believe I missed it:

PGraphicsCardboard pgc = (PGraphicsCardboard) g;
float[] headView = pgc.headView;
float[] headRotation = pgc.headRotation;

Now it all makes sense! Probably the missing packages should be moved, but it looks like my original issue actually was not an issue. I think that these three lines of code should also be mentioned in the tutorial, as they are essential for the actual interaction with the world.

Thank you again for the quick reply and also for all the amazing work that you have been doing!!!

**Closed** 2017-04-24 14:40 UTC
Labels: bug
