### ISSUE TITLE
black screen when use noLoop() in P3D mode

### ISSUE THREAD

**Issue by dodola** [processing/processing-android#194] opened 2016-02-23 08:46 UTC
when setting P3D mode and set noLoop() in setup() ,the screen is black
![device-2016-02-23-164448](https://cloud.githubusercontent.com/assets/1026848/13246189/fbfb3fe2-da4c-11e5-97ba-2ce520a15feb.png)

```java
 public void setup() {
        noLoop();
    }

    // ------------------ Processing draw --------------------

    // Draws the graph in the sketch.
    public void draw() {
        background(204);
        // Assign the horizontal value of the cursor to x
        float x = mouseX;
        // Assign the vertical value of the cursor to y
        float y = mouseY;
        line(x, y, x + 20, y - 40);
        line(x + 10, y, x + 30, y - 40);
        line(x + 20, y, x + 40, y - 40);
    }

    public void settings() {
        size(800, 600, P3D);
        smooth();
    }

```

**Comment by dodola** [comment] 2016-02-23 08:47
P2D mode is ok

**Comment by dodola** [comment] 2016-02-23 12:06
I found a solution 

```java
//PApplet.java
public void handleDraw() {
//....
//        if (canDraw()) {//Comment this

//}
}

```
The reason is GLThread and MainThread conflict

**Comment by codeanticode** [comment] 2016-02-29 21:11
Thanks for reporting. It is in fact a duplicate of https://github.com/processing/processing-android/issues/147

**Closed by codeanticode** 2016-02-29 21:11 UTC
Labels: bug, duplicate, opengl
