### ISSUE TITLE
The LoadDisplaySVG example does not work properly.

### ISSUE THREAD

**Issue by EmmanuelPil** [processing/processing-android#529] opened 2019-05-14 21:22 UTC
The shape function does not place its childs at the proper location.
Running the example sketch I get this image:
![Screenshot_2019-05-14-17-32-02](https://user-images.githubusercontent.com/31894775/57732734-1dd08700-7674-11e9-9b62-cbc34b91b360.jpg)
Modifying the screen size I get:
![Screenshot_2019-05-14-17-48-45](https://user-images.githubusercontent.com/31894775/57732859-64be7c80-7674-11e9-9428-04706c416721.jpg)
The same result I see  using APDE.
Edit: Using on Samsung tablet 9.6 E  running KiKat 4.4 and also on Samsung phone S4 running Lollipop. 5.1

**Comment by EmmanuelPil** [comment] 2019-05-19 19:57
Well, I found the culprit.
I have edited the bot1.svg file taking out all groups and added id's for all the shapes to find out why the eyes didn't go to the right position.
If someone finds it useful you can download the file here [https://drive.google.com/file/d/1H3l0p1X1tGREen7rf7zCm9iW94UWk9pl/view?usp=drivesdk](url)
After commenting-out the shapes one by one I found out that you have to leave out the following parameter "  transform="matrix(0.8929 -0.4502 0.4502 0.8929 -53.4242 36.5359)"  "
Processing goes nuts with this, and I do not have the knowledge to change the Processing core, so I hope someone can fix this.

**Comment by codeanticode** [comment] 2019-10-14 03:08
@EmmanuelPil from what I understand this is due to editing the svg and not a bug in the mode (btw, you should see the same behavior in the Java mode)... so I will close the issue. Feel free to comment/reopen if you have any other updates. Thank you!

**Closed by codeanticode** 2019-10-14 03:08 UTC
