### ISSUE TITLE
touches Array sometimes doesn't remove objects if touch has ended

### ISSUE THREAD

**Issue by JonLit** [processing/processing-android#714] opened 2022-11-27 01:54 UTC
With this code example:
```processing
void setup() {
  fullScreen();
}

void draw() {
  background(0);
  fill(255);
  for (TouchEvent.Pointer p : touches) {
    circle(p.x, p.y, 400);
  }
}
```
If I touch with one finger, a circle is displayed (at it's position)
If I touch with a second finger, a second circle is displayed
If I pull up the second finger without changing the position of the first one, the second circle still is being displayed
Only if I move or let go of the first finger, the second circle also disappeares.

Interestingly, the `touchEnded()` function is still correctly executed when letting go of the second finger.

It's easiest to test this by holding one finger steadily and then tapping with a second.

Tested on the following devices:
```text
moto g5 (LineageOS 19.1 / Android 11)     : Bug occured
Xiaomi 12 Lite (Android 12)               : Bug occured
Samsung Galaxy A5 2016 (Android 7)        : Bug occured
Honor 9X Lite (Android 9)                 : Bug DIDN'T occur
```
Video Links:
[Xiaomi 12 Lite (Android 12)](https://youtu.be/le-x3YV3oC4)
[Galaxy A5 2016 (Android 7)](https://youtube.com/shorts/RdFjVRcQMLE)
[Motorola moto g5 (LineageOS 19.1 / Android 11)](https://youtu.be/JfKYAoTXpKY)
I don't have a Video of the Honor 9X Lite unfortunately (maybe I'll make one the next few days)

**Comment by dfkettle** [comment] 2022-12-11 18:44
I think this may be the same issue as #553.

**Comment by codeanticode** [comment] 2023-01-22 16:07
Closing and tagging as duplicate of #553

**Closed by codeanticode** 2023-01-22 16:07 UTC
Labels: duplicate
