### ISSUE TITLE
Rendering Slower in OpenGL (P2D/P3D) than default

### ISSUE THREAD

**Issue by rich-gg** [processing/processing-android#204] opened 2016-04-05 15:37 UTC
**!! the previous occurrence of this issues hasn't been adressed because I made the mistake of giving 2 exemples of "Rendering Slower in OpenGL **

so here it is: 

frame rate is lower in P2D that Default

```

    int cx, cy;
    float alph = 0;

    @Override
    public void settings() {
        fullScreen();
    }

    @Override
    public void setup() {

        cx = width/2;
        cy = height/2;

    }

    @Override
    public void draw() {

        background(128, 255, 0);

        textSize(40);
        text(frameRate, 20, 50);

        noFill();

        pushMatrix();
        translate(cx, cy);
        rotate(alph);

        for (int i = -9; i < 10; i++) {
            for (int j = -9; j < 10; j++) {
                ellipse(100 * i, 100 * j, 80, 80);
            }
        }

        popMatrix();

        alph += 0.005;

    }
```
running it on processing on my PC, I get 40 FPS with default renderder and 60 with P2D
on my android (using android studio and my Nvidia Shield K1) I get :

default render : 24 FPS
P2D render : 8 FPS

the use of pushMatrix and the rotate() only help to see the frame rate, it doesn't impact FPS

**Comment by codeanticode** [comment] 2016-04-05 22:02
Duplicate of https://github.com/processing/processing-android/issues/203

**Closed by codeanticode** 2016-04-05 22:02 UTC
Labels: duplicate
