### ISSUE TITLE
Backspace key doesnt call keyReleased() 

### ISSUE THREAD

**Issue by hunterkiddo** [processing/processing-android#458] opened 2018-05-07 07:45 UTC
I'm using processing Android version, so I'm using the android keyboard to edit a String. A very weird and unwanted behavior has come up where for each key I press, I have to press the backspace key that many times before the backspace key starts calling the keyReleased

My code:
`void keyReleased() {`
`println("key released: " + keyCode);`
`if (key == ENTER || key == RETURN || keyCode == 66) {`
`closeKeyboard();`
`partySave.setString(0, "name", popUp.returnInput()); //set name`
`} else {`
`popUp.update();`
`}`
`break;`
`}`

and the popup.update() code:
`void update() {`
`key = newKey;`
`if (newKey != CODED) {`
`if ((newKey >= 'A' && newKey <= 'Z') || (newKey >= 'a' && newKey <= 'z')) {`
`input += newKey;`
`}`
`} else if ((key == BACKSPACE || key == DELETE || keyCode == 67) && input.length() > 0) {`
`println("backspace");`
`input = input.substring(0, input.length() - 1);`
`} else {`
`println("key is coded");`
`}`
`}`

If backspace is the first thing I press, then it calls it no problem. If I press 'a' and then 'backspace;' 'a' will be pressed, but 'backspace' won't be. If I press 'a' and then 'backspace,' and then 'backspace' again, it will type 'a' and then delete 'a' after the second press of 'backspace.' How can I get it to call keyPressed() every single time, or at least be able to use the backspace key every single time. Thank you!

(I even opened the keyboard input example provided by processing and loaded it up on android to see if it had the same behavior, and it does). My prediction is that there is some string that gets handled by the keyboard, and it only calls the backspace as a key when that string becomes empty; I just can't find information on it.

**Comment by tms-martins** [comment] 2018-05-09 14:31
This might not be much help, but I believe I ran into a similar issue a few years ago. 

My guess at the time was that Android is doing some extra things when handling input - e.g. presenting suggestions and all that. So the keyboard would work best with an actual Android UI element (like a EditText object) rather than a string composed in Processing.

If that's the case, I might try turning of Predictive Text and AutoCorrect in the virtual keyboard; and see if the behavior changes somehow. That may be a workaround, especially if you can disable these through code in the app.

**Tip**: to post code, use the "insert code" button **<>** in the editor or delimit the code with triple backticks ```, makes it more readable ;)

**Comment by codeanticode** [comment] 2018-05-23 20:43
@hunterkiddo thanks for pointing this out. I can reproduce the issue, and the solution may be somewhat involved. On one hand, the documentation for KeyEvent states:

> As soft input methods can use multiple and inventive ways of inputting text, there is no guarantee that any key press on a soft keyboard will generate a key event: this is left to the IME's discretion, and in fact sending such events is discouraged ... In particular, the default software keyboard will never send any key event to any application targetting Jelly Bean or later, and will only send events for some presses of the delete and return keys to applications targetting Ice Cream Sandwich or earlier. 

There is also a lengthy thread on StackOverflow on this issue:

https://stackoverflow.com/questions/18581636/android-cannot-capture-backspace-delete-press-in-soft-keyboard/34857618#34857618

which links to a bug on Android's tracker:

https://issuetracker.google.com/issues/36964165

that's marked as "Won't Fix (Intended behavior)". For the time being, I would recommend you to use a different key in your app.

**Closed** 2019-10-27 06:22 UTC
Labels: core
