### ISSUE TITLE
Sketch reset when screen orientation changed 

### ISSUE THREAD

**Issue by aymentoumi** [processing/processing-android#126] opened 2015-07-25 19:15 UTC
I remark that when screen orientation changed the applet reset and the sketch code restart from the beginning so the variables are set to their initial values and the setup method executed again.

**Comment by codeanticode** [comment] 2015-08-11 15:42
Duplicate of https://github.com/processing/processing-android/issues/3

**Closed by codeanticode** 2015-08-11 15:42 UTC
Labels: duplicate
