### ISSUE TITLE
Please don’t add usage of lambda expressions/forEach to the library code. There is a significant performance penalty when using them.

### ISSUE THREAD

**Issue by hadihadi01111** [processing/processing-android#539] opened 2019-07-03 12:35 UTC
Please don’t add usage of lambda expressions/forEach to the library code. There is a significant performance penalty when using them.

_Originally posted by @Spongman in https://github.com/processing/p5.js/issues/3758#issuecomment-507922753_

**Comment by kfrajer** [comment] 2019-07-20 18:47
@hadihadi01111 This is the Android Processing repo. You are referencing js and P5.js. Close it if this was done by mistake. Or clarify your goals with this post and how it related to this project.

**Comment by codeanticode** [comment] 2019-07-21 15:22
Sounds like the issue is related to p5, to tagging as invalid and closing. @hadihadi01111 feel free to comment below if you think this could affect Android as well.

**Closed by codeanticode** 2019-07-21 15:22 UTC
Labels: invalid
