### ISSUE TITLE
P2D, P3D, and OPENGL options in size() crash sketch in emulator

### ISSUE THREAD

**Issue by XshadowlynxX** [processing/processing-android#96] opened 2015-02-02 07:21 UTC
Whenever I try and do something like this:
```Java
size(displayWidth, displayHeight, P3D);
```
The processing sketch running in android mode crashes.
This however works fine:
```Java
size(displayWidth, displayHeight, JAVA2D);
```

Any keyword other then JAVA2D crashes the sketch.
I think the problem is related to:
```Java
if (rendererName.equals(JAVA2D)) {
// JAVA2D renderer
surfaceView = new SketchSurfaceView(this, sw, sh,
(Class<? extends PGraphicsAndroid2D>) rendererClass);
} else if (PGraphicsOpenGL.class.isAssignableFrom(rendererClass)) {
// P2D, P3D, and any other PGraphicsOpenGL-based renderer
surfaceView = new SketchSurfaceViewGL(this, sw, sh,
(Class<? extends PGraphicsOpenGL>) rendererClass);
} else {
// Anything else
String message = String.format(
"Error: Unsupported renderer class: %s", rendererName);
throw new RuntimeException(message);
}
```

**Comment by codeanticode** [comment] 2015-05-18 21:08
Hi, unfortunately we haven't had time to add support for P2D/P3D sketches in the Android emulator. I know that for a [while now](http://www.learnopengles.com/android-emulator-now-supports-native-opengl-es2-0/) the emulator has been supporting native OpenGL ES 2.0, but it never was priority for us to figure out how to enable that support for Processing sketches. I'm marking this issue as an enhancement, and of course patches/contributions are very welcome!

**Comment by XshadowlynxX** [comment] 2015-05-18 21:10
Thanks for the info. Good job so far. It’s great that 2D Processing even works!

> On May 18, 2015, at 3:08 PM, codeanticode <notifications@github.com> wrote:
> 
> Hi, unfortunately we haven't had time to add support for P2D/P3D sketches in the Android emulator. I know that for a while now <http://www.learnopengles.com/android-emulator-now-supports-native-opengl-es2-0/> the emulator has been supporting native OpenGL ES 2.0, but it never was priority for us to figure out how to enable that support for Processing sketches. I'm marking this issue as an enhancement, and of course patches/contributions are very welcome!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/processing/processing-android/issues/96#issuecomment-103211474>.
> 


Tavi Kohn
X <mailto://XshadowlynxX@gmail.com>shadowlynxX@gmail.com <mailto://XshadowlynxX@gmail.com>

**Comment by codeanticode** [comment] 2016-06-10 14:10
duplicate of #10

**Closed by codeanticode** 2016-06-10 14:10 UTC
Labels: duplicate, enhancement
